### ISSUE TITLE
Error Can't call method on [object HTMLALLCollection]

### ISSUE THREAD

**Issue by leocxy** [luoye-fe/dom-inspector#17]
Hello, when I try to init the object, it throws this error: Can't call method on  [object HTMLAllCollection].  Does anyone have any idea about this? Thank you

Below is the script that caused this fatal error.
`inspector = new DomInspector({root: 'body'});`

**Comment by luoye-fe** [comment]
try version `1.2.4-beta.0`

**Comment by leocxy** [comment]
> try version `1.2.4-beta.0`

Yes. It is working now. Thank you for your update.

**Comment by luoye-fe** [comment]
ok, the official version has been updated, use `dom-inspector@1.2.4`.
