### ISSUE TITLE
How to attach node-inspector to page loaded in iframe or object?

### ISSUE THREAD

**Issue by ratkorle** [luoye-fe/dom-inspector#5]
First must say, great job!

I am trying to inspect page loaded to my Angular component in iframe or <object id='pageFrame'>, but I can't get that done. I have tried to set root to #pageFrame but still it inspects whole component.

Any ideas how do I do this?

**Comment by luoye-fe** [comment]
If main page and iframe not same origin, unable to inspect node in iframe. 

You can insert script in iframe. Or provide pseudocode.

**Comment by ratkorle** [comment]
How do I do that. I just need to load another page and inspect it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by luoye-fe** [comment]
For example, your main page:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <iframe id="iframe" src="https://www.google.com/" frameborder="0"></iframe>
    <script type="text/javascript" src="dom-inspector.js"></script>
    <script>
        const inspector = new DomInspector({
            root: '#iframe'
        });
        inspector.enable();
    </script>
</body>

</html>
```

You only can inspect iframe tag, can't inspect any element in `google` page.

If want inspect element in iframe page, you should add script in iframe.

Or ensure your main page and iframe page in same origin, look [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) about `CORS`. Then you can do like this:

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <iframe id="iframe" src="[your iframe page url]"></iframe>
    <script type="text/javascript" src="dom-inspector.js"></script>
    <script>
        document.getElementById("iframe").onload = () => {
            const inspector = new DomInspector({
                // get iframe element by `contentWindow`
                root: document.getElementById("iframe").contentWindow.document.querySelector('h1')
            });

            inspector.enable();
        }
    </script>
</body>

</html>

```

**Comment by luoye-fe** [comment]
ping?

**Comment by melehin** [comment]
Hi, @luoye-fe!

My iframe page is shifted relative to the left edge of main page.

![image](https://user-images.githubusercontent.com/3829167/73953830-c7eaf000-4922-11ea-8228-bd99c00c5c12.png)


Tell me, please, how can I fix such a problem?

**Comment by luoye-fe** [comment]
Maybe, after the page loaded, you changed the browser size?

If so, you can listen the change event, and renew the dom-inspector instance.

**Comment by melehin** [comment]
Please look at this example: https://codepen.io/fedormelexin/project/full/ZeWdPj

![image](https://user-images.githubusercontent.com/3829167/74525888-08aac080-4f44-11ea-9d45-8b77b211ead3.png)

**Comment by melehin** [comment]
I am resolved my problem by a workaround.

## Workaround ##
Patched this line (for my use case when inspect the iframe body)
https://github.com/luoye-fe/dom-inspector/blob/b1e9559b53e2ff3d31a323a4a0fbb3c3a3780412/src/index.js#L121
to
```javascript
this.root.appendChild(parent);
```

## Usage ##
```javascript
// Load style.css as string over raw-loader
import dom_inspector_style from '!raw-loader!dom-inspector/src/style.css';

// Injection the DomInspector style into the iframe
var style = document.createElement('style');
style.textContent = dom_inspector_style;
document.getElementById("iframe").contentDocument.head.appendChild(style);

// Connect the DomInspector to the iframe
const inspector = new DomInspector({
  root: document.getElementById("iframe").contentDocument.body,
});
inspector.enable();
```
![image](https://user-images.githubusercontent.com/3829167/77895926-ea4d1a00-7290-11ea-89c6-f8c7df0d6c51.png)

**Comment by luoye-fe** [comment]
👍

`dom-inspector@1.2.3-beta.0` 

Follow your workaround, latest baet version has been released. 

Try vertsion `dom-inspector@1.2.3-beta.0`, if there is no problem, give me a reply, i will release official version.

THX :)

**Comment by melehin** [comment]
Thanks it works!

But only with css injection, as expected.

And I got another problem inside the iframe. 
The getMaxZIndex function uses document.all for the main page, not for current this.root + document.all
https://github.com/luoye-fe/dom-inspector/blob/b1e9559b53e2ff3d31a323a4a0fbb3c3a3780412/src/dom.js#L82
![image](https://user-images.githubusercontent.com/3829167/77910586-cd244580-72a8-11ea-8496-7ac65c67b4d6.png)

**Comment by luoye-fe** [comment]
This kind of scene, if `dom-inspector` gets `maxZIndex` value, cant cover all usage, maybe you need a new instance option?

Just like：

```js
const instance = DomInspector({
  root: 'body',
  maxZIndex: 99,
})
```

**Comment by melehin** [comment]
It would be great!

And good to add a bit of backward compatibility so that the value is optional.
(pseudo code)
```javascript
Math.max(maxZIndex, getMaxZIndex())
```
or rename maxZIndex to minZIndex within the meaning of Math.max
```javascript
Math.max(minZIndex, getMaxZIndex())
```

**Comment by luoye-fe** [comment]
If `maxZIndex` option has been specified,  instance should not modify it, otherwise, the user must understand the internal logic.

Let me add the option, then you try it.

**Comment by luoye-fe** [comment]
@melehin `dom-inspector@1.2.3-beta.1`

**Comment by melehin** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/3829167/77984955-81b37b00-732c-11ea-8547-a250385d4e59.png)

**Comment by luoye-fe** [comment]
OK, I release the official version.
